version: '3'

services:
  mongodb:
    build:
      context: ./database
      dockerfile: Dockerfile.mongodb
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongodb

  web:
    build:
      context: ./web
      dockerfile: Dockerfile.web
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - api

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    networks:
      - app-network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

  sonar-db:
    image: postgres:latest
    networks:
      - app-network
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
  postgresql_data:
