name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image for API
        run: docker build -t my-api-image ./api

      - name: Run Unit Tests
        run: ./tests/run-tests.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Image to Docker Hub
        run: docker push my-api-image

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Kubernetes context
        uses: azure/setup-kubectl@v1
        with:
          version: "v1.20.0"

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
